//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplainableAIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int SurveryID { get; set; }
        public int QuestionID { get; set; }
        public int OfferedAnswerID { get; set; }
        public int PersonID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TimeTaken { get; set; }
        public string SelectedImageURL { get; set; }
        public int AnswerID { get; set; }
        public Nullable<System.DateTime> AnswerDateTime { get; set; }
    
        public virtual person person { get; set; }
    }
}
