//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplainableAIWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class explainableaidbEntities2 : DbContext
    {
        public explainableaidbEntities2()
            : base("name=explainableaidbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer> answers { get; set; }
        public virtual DbSet<offeredanswer> offeredanswers { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<survery_question_answer> survery_question_answer { get; set; }
        public virtual DbSet<survey> surveys { get; set; }
        public virtual DbSet<survey_question> survey_question { get; set; }
        public virtual DbSet<iteration> iterations { get; set; }
        public virtual DbSet<survery_iterations> survery_iterations { get; set; }
        public virtual DbSet<person_survey> person_survey { get; set; }
    }
}
