//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplainableAIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offeredanswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public offeredanswer()
        {
            this.survery_question_answer = new HashSet<survery_question_answer>();
        }
    
        public int OfferedAnswerID { get; set; }
        public string AnswerText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survery_question_answer> survery_question_answer { get; set; }
    }
}
