//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplainableAIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_question
    {
        public int SurveryID { get; set; }
        public int QuestionID { get; set; }
        public string PhotoFolderName { get; set; }
        public Nullable<bool> SkipOnRepeat { get; set; }
    
        public virtual question question { get; set; }
        public virtual survey survey { get; set; }
    }
}
