//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplainableAIWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survery_iterations
    {
        public int SurveyID { get; set; }
        public int IterationID { get; set; }
        public int QuestionID { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> NextOrderNumber { get; set; }
    }
}
